# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aviso(object):
    '''

    Código obtenido del fichero aviso.ui generado con QtDesigner.
    Contiene la interfaz gráfica de aviso

    '''
    def setupUi(self, aviso):
        aviso.setObjectName("aviso")
        aviso.setWindowModality(QtCore.Qt.NonModal)
        aviso.resize(400, 300)
        aviso.setModal(True)
        self.btnboxaviso = QtWidgets.QDialogButtonBox(aviso)
        self.btnboxaviso.setGeometry(QtCore.QRect(110, 210, 156, 23))
        self.btnboxaviso.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnboxaviso.setCenterButtons(False)
        self.btnboxaviso.setObjectName("btnboxaviso")
        self.lblaviso = QtWidgets.QLabel(aviso)
        self.lblaviso.setGeometry(QtCore.QRect(120, 140, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblaviso.setFont(font)
        self.lblaviso.setObjectName("lblaviso")
        self.label = QtWidgets.QLabel(aviso)
        self.label.setGeometry(QtCore.QRect(160, 60, 61, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/warning.png"))
        self.label.setObjectName("label")

        self.retranslateUi(aviso)
        QtCore.QMetaObject.connectSlotsByName(aviso)

    def retranslateUi(self, aviso):
        _translate = QtCore.QCoreApplication.translate
        aviso.setWindowTitle(_translate("aviso", "Dialog"))
        self.lblaviso.setText(_translate("aviso", "DESEA SALIR?"))
