# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowCal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowCal(object):
    '''

    Código obtenido del fichero windowCal.ui generado con QtDesigner.
    Contiene la interfaz gráfica del calendario

    '''
    def setupUi(self, windowCal):
        windowCal.setObjectName("windowCal")
        windowCal.resize(311, 183)
        self.calendar = QtWidgets.QCalendarWidget(windowCal)
        self.calendar.setGeometry(QtCore.QRect(0, 0, 312, 183))
        self.calendar.setObjectName("calendar")

        self.retranslateUi(windowCal)
        QtCore.QMetaObject.connectSlotsByName(windowCal)

    def retranslateUi(self, windowCal):
        _translate = QtCore.QCoreApplication.translate
        windowCal.setWindowTitle(_translate("windowCal", "Seleccione fecha"))
